### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by q4a** [q4a/juffed#2]
Top priority tasks:
- [ ] compare unsaved files with meld
- [ ] dark theme

Low priority tasks (unnecessary?):
- [ ] check and allow to use grep for "Find in files"

---
Merged to maser in https://github.com/Mezomish/juffed/commit/73ad560ebf0441d27e1544e0f349fbb3b840882f
- [x] apply all useful patches
- [x] add Linux CI
- [x] show full path in window title
- [x] FindInFiles: open popup window with `Ctrl + Shift + F`
- [x] FindInFiles: add search with `*.cpp *.hpp *.c *.h *.inl`
- [x] FindInFiles: restore last searched text
- [x] add shortcut `Alt+Z` to "Move to other panel"

Find in files features:
1. Shortcut to open Popup window:
- Visual Studio: `Ctrl + Shift + F`
- Notepad++: `Ctrl + Shift + F`
- Qt Creator: `Ctrl + Shift + F`
- Geany: `Ctrl + Shift + F`
- Juffed: `Ctrl + Alt + F` - upstream. Develop: `Ctrl + Shift + F` - https://github.com/q4a/juffed/commit/987f31011728b88db0af750a3ab1e8dde51d4561

2. Search with few patterns (like `*.cpp *.hpp *.c *.h *.inl`):
- Visual Studio: `*.cpp;*.hpp;*.c;*.h;*.inl`
- Notepad++: `*.cpp *.hpp *.c *.h *.inl`
- Qt Creator: `*.cpp, *.hpp, *.c, *.h, *.inl`
- Geany: `*.cpp *.hpp *.c *.h *.inl`
- Juffed: `*.cpp;*.hpp;*.c;*.h;*.inl` - upstream. Develop: all 3 version supported - https://github.com/q4a/juffed/commit/35fe1c7a3f4ea44d195b7a86f200429a5ffdf89c
